project_id = "gdgnhxjpsgwdzmhicrbd"

[auth]
site_url = "https://nuknuk.ch"
additional_redirect_urls = ["https://nuknuk.ch/konto", "https://nuknuk.ch/paesse", "https://nuknuk.ch/paesse?produkt=*"]

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8
