"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";
import { Booking, Service, dateLabel, isoDate, money, statusLabel, timeLabel } from "@/lib/volta";
import Studio from "@/components/Studio";

const hours=Array.from({length:15},(_,i)=>`${String(i+9).padStart(2,"0")}:00`),tables=Array.from({length:8},(_,i)=>i+1);
type GroupInquiry={id:string;reference:string;desired_date:string;preferred_time:string|null;guest_count:number;first_name:string;last_name:string;email:string;phone:string;company:string;message:string;status:string;created_at:string};
function Icon({name}:{name:string}){const p:Record<string,React.ReactNode>={calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></>,booking:<><path d="M6 2h9l5 5v15H6z"/><path d="M14 2v6h6M9 13h7M9 17h5"/></>,tables:<><rect x="3" y="6" width="18" height="11" rx="2"/><path d="M7 17v4M17 17v4M8 10h8"/></>,settings:<><circle cx="12" cy="12" r="3"/><path d="M19 15l2 2-4 4-2-2M5 9 3 7l4-4 2 2"/></>,plus:<path d="M12 5v14M5 12h14"/>};return <svg className="icon" viewBox="0 0 24 24">{p[name]}</svg>}

export default function Home(){
 const [pin,setPin]=useState(""),[unlocked,setUnlocked]=useState(false),[date,setDate]=useState(isoDate(new Date())),[bookings,setBookings]=useState<Booking[]>([]),[groups,setGroups]=useState<GroupInquiry[]>([]),[services,setServices]=useState<Service[]>([]),[active,setActive]=useState<Booking|null>(null),[view,setView]=useState<"calendar"|"bookings"|"groups"|"services"|"settings">("calendar"),[query,setQuery]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(usePin=pin){setBusy(true);setError("");const [{data,error:e},{data:groupData,error:groupError}]=await Promise.all([supabase.rpc("vp_admin_bookings",{p_pin:usePin,p_from:date,p_to:date}),supabase.rpc("vp_admin_group_inquiries",{p_pin:usePin})]);setBusy(false);if(e||groupError){setUnlocked(false);const message=e?.message||groupError?.message||"";setError(message.includes("Admin-PIN")?"Der Admin-PIN stimmt nicht.":message);return}setBookings(data||[]);setGroups(groupData||[]);setUnlocked(true);sessionStorage.setItem("vp-admin-pin",usePin)}
 // Restore a PIN only for the current browser session.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{supabase.from("vp_services").select("*").order("sort_order").then(({data})=>setServices(data||[]));const saved=sessionStorage.getItem("vp-admin-pin");if(saved){setPin(saved);void load(saved)}},[]);
 // Date changes refresh the protected day view.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{if(unlocked)void load()},[date]);
 async function update(id:string,status?:Booking["status"],payment?:Booking["payment_status"]){if((status==="cancelled"||status==="no_show")&&!confirm(`Buchung wirklich als ${statusLabel[status]} markieren?`))return;setBusy(true);const {error:e}=await supabase.rpc("vp_admin_update_booking",{p_pin:pin,p_id:id,p_status:status||null,p_payment:payment||null});if(e)setError(e.message);else{await load();setActive(null)}setBusy(false)}
 const filtered=useMemo(()=>bookings.filter(b=>`${b.customer_name} ${b.reference} ${b.customer_email}`.toLowerCase().includes(query.toLowerCase())),[bookings,query]);
 const revenue=bookings.filter(b=>b.status!=="cancelled").reduce((n,b)=>n+(b.price_cents||0),0),usedHours=bookings.filter(b=>["request","confirmed","checked_in"].includes(b.status)).reduce((n,b)=>n+b.table_ids.length*((new Date(b.ends_at).getTime()-new Date(b.starts_at).getTime())/3600000),0);
 if(!unlocked)return <main className="admin-login"><div className="login-brand">VOLTA <span>PONG!</span></div><form onSubmit={(e:FormEvent)=>{e.preventDefault();void load()}}><p className="eyebrow">TEAM-BEREICH</p><h1>Spielbetrieb öffnen.</h1><p>Mit dem sechsstelligen Team-PIN erhältst du Zugriff auf Live-Buchungen, Kontaktdaten, Check-in und Zahlungen.</p><label>Admin-PIN<input autoFocus inputMode="numeric" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))}/></label>{error&&<div className="form-error">{error}</div>}<button disabled={pin.length<6||busy}>{busy?"Wird geöffnet …":"Team-Ansicht öffnen"}</button><a href="/buchen">Zur öffentlichen Buchungsseite →</a></form></main>;
 return <div className="app-shell"><aside className="sidebar"><div className="brand">VOLTA<br/><span>PONG!</span></div><nav>{([['calendar','calendar','Kalender'],['bookings','booking','Buchungen'],['groups','booking','Gruppenanfragen'],['services','tables','Übersicht'],['settings','settings','Services & Ressourcen']] as const).map(([id,icon,label])=><button key={id} className={`nav-item ${view===id?'active':''}`} onClick={()=>setView(id)}><Icon name={icon}/>{label}{id==='bookings'&&<span className="nav-count">{bookings.length}</span>}{id==='groups'&&groups.length>0&&<span className="nav-count">{groups.length}</span>}</button>)}</nav><div className="sidebar-bottom"><a className="nav-item" href="/buchen"><Icon name="plus"/>Neue Buchung</a><button className="nav-item" onClick={()=>{sessionStorage.removeItem("vp-admin-pin");setUnlocked(false);setPin("")}}>Sperren</button></div></aside>
 <main className={`main-content ${view==='settings'?'studio-page':''}`}><header className="topbar"><div><p className="eyebrow">{view==='settings'?'ANGEBOTE · KAPAZITÄTEN · VERFÜGBARKEIT':'LIVE · EUROPE/ZURICH'}</p><h1>{view==='calendar'?dateLabel(date):view==='bookings'?'Alle Buchungen':view==='groups'?'Gruppenanfragen':view==='services'?'Angebote & Pakete':'Services & Ressourcen'}</h1></div><div className="topbar-actions">{!['settings','groups'].includes(view)&&<input className="date-input" type="date" value={date} onChange={e=>setDate(e.target.value)}/>}<a className="primary-button" href="/buchen"><Icon name="plus"/>{view==='settings'?'Buchungsseite öffnen':'Neue Buchung'}</a></div></header>{error&&<div className="form-error">{error}</div>}
 {view==='calendar'&&<><section className="stats"><article className="stat-card"><span>Buchungen</span><strong>{bookings.length}</strong><small>{bookings.filter(b=>b.status==='request').length} Anfragen</small></article><article className="stat-card"><span>Gäste</span><strong>{bookings.reduce((n,b)=>n+b.guest_count,0)}</strong><small>heute erwartet</small></article><article className="stat-card accent"><span>Auslastung</span><strong>{Math.round(usedHours/(8*15)*100)}%</strong><div className="mini-progress"><i style={{width:`${Math.min(100,usedHours/(8*15)*100)}%`}}/></div></article><article className="stat-card"><span>Reservierungswert</span><strong>{money(revenue)}</strong><small>{bookings.filter(b=>b.payment_status==='paid').length} bezahlt</small></article></section><section className="live-calendar"><div className="calendar-grid-head"><span>Zeit</span>{tables.map(t=><span key={t}>Tisch {t}<small>{t<=4?'Nord':'Süd'}</small></span>)}</div>{hours.map(h=><div className="calendar-grid-row" key={h}><time>{h}</time>{tables.map(t=>{const b=bookings.find(x=>x.table_ids.includes(t)&&timeLabel(x.starts_at)<=h&&timeLabel(x.ends_at)>h&&x.status!=='cancelled');return <div key={t}>{b&&timeLabel(b.starts_at)===h?<button className={`live-booking status-${b.status}`} onClick={()=>setActive(b)} style={{height:`calc(${Math.max(1,(new Date(b.ends_at).getTime()-new Date(b.starts_at).getTime())/3600000)} * 58px - 6px)`}}><strong>{b.customer_name}</strong><small>{b.guest_count} Pers. · {b.reference}</small></button>:null}</div>})}</div>)}</section></>}
 {view==='bookings'&&<section className="management-panel"><div className="list-toolbar"><input placeholder="Name, Referenz oder E-Mail suchen" value={query} onChange={e=>setQuery(e.target.value)}/><span>{filtered.length} Einträge</span></div><div className="management-list">{filtered.map(b=><button key={b.id} onClick={()=>setActive(b)}><time>{timeLabel(b.starts_at)}</time><span><strong>{b.customer_name}</strong><small>{services.find(s=>s.id===b.service_id)?.short_name} · Tisch {b.table_ids.join(', ')}</small></span><em className={`pill status-${b.status}`}>{statusLabel[b.status]}</em><b>{money(b.price_cents)}</b><small>{b.payment_status==='paid'?'bezahlt':'offen'}</small></button>)}{!filtered.length&&<p className="empty-message">An diesem Tag gibt es noch keine Buchungen.</p>}</div></section>}
 {view==='groups'&&<section className="management-panel group-inquiry-list"><div className="list-toolbar"><strong>{groups.length} Gruppenanfragen</strong><span>Neueste zuerst</span></div>{groups.map(g=><article key={g.id}><div><p className="eyebrow">{g.reference} · {g.status==='new'?'Neu':g.status}</p><h2>{g.first_name} {g.last_name}</h2><span>{new Intl.DateTimeFormat("de-CH",{dateStyle:"long"}).format(new Date(g.desired_date+"T12:00:00"))}{g.preferred_time?' · '+g.preferred_time.slice(0,5):''} · {g.guest_count} Personen</span></div><p>{g.message||'Keine weiteren Angaben.'}</p><div><a href={'mailto:'+g.email}>{g.email}</a><a href={'tel:'+g.phone}>{g.phone}</a>{g.company&&<span>{g.company}</span>}</div></article>)}{!groups.length&&<p className="empty-message">Noch keine Gruppenanfragen.</p>}</section>}
 {view==='services'&&<section className="service-admin-grid">{services.map(s=><article key={s.id}><span>{s.required_tables} {s.required_tables===1?'Tisch':'Tische'}</span><h2>{s.short_name}</h2><p>{s.description}</p><dl><div><dt>Personen</dt><dd>{s.min_people}{s.max_people?`–${s.max_people}`:'+'}</dd></div><div><dt>Dauer</dt><dd>{s.min_duration_hours}–{s.max_duration_hours} Std.</dd></div><div><dt>Ab</dt><dd>{s.available_from.slice(0,5)}</dd></div><div><dt>Preis</dt><dd>{s.billing==='request'?'Anfrage':s.billing==='fixed'?money(s.price_cents):`${money(s.price_cents)} / h`}</dd></div></dl></article>)}</section>}
 {view==='settings'&&<Studio pin={pin}/>}
 </main>{busy&&<div className="busy-bar">Wird aktualisiert …</div>}
 {active&&<div className="modal-backdrop" onMouseDown={()=>setActive(null)}><section className="booking-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setActive(null)}>×</button><p className="eyebrow">{active.reference}</p><h2>{active.customer_name}</h2><p>{active.customer_email}<br/>{active.customer_phone}{active.company&&<><br/>{active.company}</>}</p><div className="modal-grid"><span><small>Zeit</small>{timeLabel(active.starts_at)}–{timeLabel(active.ends_at)}</span><span><small>Tische</small>{active.table_ids.join(', ')}</span><span><small>Gäste</small>{active.guest_count}</span><span><small>Check-in-PIN</small>{active.pin_code}</span><span><small>Status</small>{statusLabel[active.status]}</span><span><small>Zahlung</small>{active.payment_status}</span></div>{active.notes&&<p className="modal-note">{active.notes}</p>}<div className="modal-actions"><button onClick={()=>update(active.id,'checked_in')}>Einchecken</button><button onClick={()=>update(active.id,undefined,active.payment_status==='paid'?'open':'paid')}>{active.payment_status==='paid'?'Als offen markieren':'Als bezahlt markieren'}</button><button className="danger" onClick={()=>update(active.id,'cancelled')}>Stornieren</button></div></section></div>}
 </div>
}
